import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import NavBar from "../component/NavBar";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Head>
        <title>Quikbet Movies</title>
        <meta
          name="description"
          content="Explora películas y guarda tus favoritas con CineColombia."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
