import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head"
import NavBar from "../component/NavBar";
import Carousel from "../component/Carousel"; // Componente que muestra el banner


const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Quikbet Movies</title>
      </Head>
        <body className={inter.className}>
          <NavBar />
          <Carousel />
          {children}
        </body>
    </html>
  );
}
